// react/yarn3-unplugged/src/App.tsx
import React, { useState } from 'react'
import './App.css'
import {
    createPromiseClient,
    createConnectTransport,
} from '@bufbuild/connect-web'
import { ElizaService } from './gen/buf/connect/demo/eliza/v1/eliza_connectweb.js'
import { IntroduceRequest } from './gen/buf/connect/demo/eliza/v1/eliza_pb.js'

function App() {
    const [name, setName] = useState<string>('')
    const [statement, setStatement] = useState<string>('')
    const [intros, setIntros] = useState<string[]>([])
    const [answers, setAnswers] = useState<string[]>([])
    const [showSayInput, setShowSayInput] = useState<boolean>(false)

    // Make the Eliza Service client
    const client = createPromiseClient(
        ElizaService,
        createConnectTransport({
            baseUrl: 'https://demo.connect.build',
        })
    )

    const say = async (sentence: string) => {
        const response = await client.say({
            sentence,
        })

        setAnswers((answers: string) => [...answers, response.sentence])
    }

    const introduce = async (name: string) => {
        const request = new IntroduceRequest({
            name,
        })

        for await (const response of client.introduce(request)) {
            setIntros((intro) => [...intro, response.sentence])
        }

        setShowSayInput(true)
    }

    const handleNameChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        setName(event.target.value)
    }

    const handleStatementChange = (
        event: React.ChangeEvent<HTMLInputElement>
    ) => {
        setStatement(event.target.value)
    }

    const handleSay = () => {
        say(statement)
    }

    const handleIntroduce = () => {
        introduce(name)
    }

    return (
        <div className="app">
            <header className="app-header">
                <div className="app-title">
                    <div>
                        <h1>Eliza</h1>
                    </div>
                </div>
                <p className="prompt-text">What is your name?</p>
                <div>
                    <input
                        type="text"
                        className="text-input"
                        value={name}
                        onChange={handleNameChange}
                    />
                    <button onClick={handleIntroduce}>Introduce</button>
                </div>
                <div className="intro-container">
                    {intros.map((intro, i) => {
                        return (
                            <p className="resp-text" key={`resp${i}`}>
                                {intro}
                            </p>
                        )
                    })}
                </div>
                {showSayInput ? (
                    <div>
                        <input
                            type="text"
                            className="text-input"
                            value={statement}
                            onChange={handleStatementChange}
                        />
                        <button onClick={handleSay}>Say</button>
                    </div>
                ) : (
                    <React.Fragment />
                )}
                <div className="intro-container">
                    {answers.map((answer: string) => {
                        return <p className="resp-text">{answer}</p>
                    })}
                </div>
            </header>
        </div>
    )
}

export default App

// angular/eliza/src/app/app.component.ts
import { Component, Inject } from '@angular/core'
import { ObservableClient } from 'src/connect/observable-client'
import { ElizaService } from 'src/gen/buf/connect/demo/eliza/v1/eliza_connectweb'

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css'],
})
export class AppComponent {
    title = 'eliza'
    constructor(
        @Inject(ElizaService)
        private client: ObservableClient<typeof ElizaService>
    ) {}

    ngOnInit() {
        this.client.say({ sentence: 'something' }).subscribe((next) => {
            console.log(next.sentence)
        })
    }
}

<style>
</style>

<!-- Toolbar -->
<div class="app">
    <header class="app-header">
        <div class="app-title">
            <div>
                <h1>{{ title }}</h1>
            </div>
        </div>
        <p class="prompt-text">What is your name?</p>
        <div>
            <input type="text" class="text-input" />
            <button>Introduce</button>
        </div>
        <div class="intro-container">
                <p class="resp-text">intro text</p>
        </div>
            <div>
                <input type="text" class="text-input"  />
                <button >Say</button>
            </div>
        <div class="intro-container">
                <p class="resp-text">answer</p>
        </div>
    </header>
</div>
