// svelte/src/routes/index.svelte
<script lang="ts">
    import {
        createPromiseClient,
        createConnectTransport,
    } from '@bufbuild/connect-web'
    import { ElizaService } from '../gen/buf/connect/demo/eliza/v1/eliza_connectweb.js'
    import { IntroduceRequest } from '../gen/buf/connect/demo/eliza/v1/eliza_pb.js'

    const INTRO_DELAY_MS = 500

    let name = ''
    let statement = ''
    let intros: string[] = []
    let answers: string[] = []
    let showSayInput = false

    // Make the Eliza Service client
    const client = createPromiseClient(
        ElizaService,
        createConnectTransport({
            baseUrl: 'https://demo.connect.build',
        })
    )

    const say = async () => {
        const response = await client.say({
            sentence: statement,
        })

        answers = [...answers, response.sentence]
    }

    const introduce = async () => {
        const request = new IntroduceRequest({
            name,
        })

        let resps: string[] = []
        for await (const response of client.introduce(request)) {
            resps.push(response.sentence)
        }
        setTimeout(() => {
            showSayInput = true
        }, resps.length * INTRO_DELAY_MS)

        for (var i = 0; i < resps.length; i++) {
            ;((i) => {
                setTimeout(() => {
                    intros = [...intros, resps[i]]
                }, INTRO_DELAY_MS * (i + 1))
            })(i)
        }
    }
</script>

<div class="app">
    <header class="app-header">
        <div class="app-title">
            <div>
                <h1>Eliza</h1>
            </div>
        </div>
        <p class="prompt-text">What is your name?</p>
        <div>
            <input type="text" class="text-input" bind:value={name} />
            <button on:click={introduce}>Introduce</button>
        </div>
        <div class="intro-container">
            {#each intros as intro}
                <p class="resp-text">{intro}</p>
            {/each}
        </div>
        {#if showSayInput}
            <div>
                <input type="text" class="text-input" bind:value={statement} />
                <button on:click={say}>Say</button>
            </div>
        {/if}
        <div class="intro-container">
            {#each answers as answer}
                <p class="resp-text">{answer}</p>
            {/each}
        </div>
    </header>
</div>

<style>
    .app {
        text-align: center;
    }

    .app-header {
        background-color: #282c34;
        min-height: 100vh;
        display: flex;
        flex-direction: column;
        align-items: center;
        font-size: calc(10px + 2vmin);
        color: white;
    }

    .app-title {
        display: flex;
        justify-content: space-evenly;
        align-items: center;
    }

    .prompt-text {
        margin: 0 0 15px 0;
    }
    .intro-container {
        margin: 15px;
    }
    .resp-text {
        font-size: 1rem;
        margin: 5px;
    }
    .text-input {
        width: 200px;
    }

    h1 {
        margin-bottom: 0;
    }
</style>

// remix/eliza/app/routes/index.tsx
import React, { useState } from 'react'
import {
    createPromiseClient,
    createConnectTransport,
} from '@bufbuild/connect-web'
import { ElizaService } from '../gen/buf/connect/demo/eliza/v1/eliza_connectweb.js'
import { IntroduceRequest } from '../gen/buf/connect/demo/eliza/v1/eliza_pb.js'

export default function Index() {
    const [name, setName] = useState<string>('')
    const [statement, setStatement] = useState<string>('')
    const [intros, setIntros] = useState<string[]>([])
    const [answers, setAnswers] = useState<string[]>([])
    const [showSayInput, setShowSayInput] = useState<boolean>(false)

    const INTRO_DELAY_MS = 500

    // Make the Eliza Service client
    const client = createPromiseClient(
        ElizaService,
        createConnectTransport({
            baseUrl: 'https://demo.connect.build',
        })
    )

    const say = async (sentence: string) => {
        const response = await client.say({
            sentence,
        })

        setAnswers((answers) => [...answers, response.sentence])
    }

    const introduce = async (name: string) => {
        const request = new IntroduceRequest({
            name,
        })
        let resps: string[] = []
        for await (const response of client.introduce(request)) {
            resps.push(response.sentence)
        }
        setTimeout(() => {
            setShowSayInput(true)
        }, resps.length * INTRO_DELAY_MS)
        for (var i = 0; i < resps.length; i++) {
            ;(function (i) {
                setTimeout(function () {
                    setIntros((intro) => [...intro, resps[i]])
                }, INTRO_DELAY_MS * (i + 1))
            })(i)
        }
    }

    const handleNameChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        setName(event.target.value)
    }

    const handleStatementChange = (
        event: React.ChangeEvent<HTMLInputElement>
    ) => {
        setStatement(event.target.value)
    }

    const handleSay = () => {
        say(statement)
    }

    const handleIntroduce = () => {
        introduce(name)
    }

    return (
        <div className="App">
            <header className="App-header">
                <div className="app-title">
                    <div>
                        <h1>Eliza</h1>
                    </div>
                </div>
                <p className="prompt-text">What is your name?</p>
                <div>
                    <input
                        type="text"
                        className="text-input"
                        value={name}
                        onChange={handleNameChange}
                    />
                    <button onClick={handleIntroduce}>Introduce</button>
                </div>
                <div className="intro-container">
                    {intros.map((intro, i) => {
                        return (
                            <p className="resp-text" key={`resp${i}`}>
                                {intro}
                            </p>
                        )
                    })}
                </div>
                {showSayInput ? (
                    <div>
                        <input
                            type="text"
                            className="text-input"
                            value={statement}
                            onChange={handleStatementChange}
                        />
                        <button onClick={handleSay}>Say</button>
                    </div>
                ) : (
                    <React.Fragment />
                )}
                <div className="intro-container">
                    {answers.map((answer: string) => {
                        return <p className="resp-text">{answer}</p>
                    })}
                </div>
            </header>
        </div>
    )
}
