// angular/src/app/app.component.ts
import { Component, Inject } from '@angular/core'
import { ObservableClient } from 'src/connect/observable-client'
import { ElizaService } from 'src/gen/buf/connect/demo/eliza/v1/eliza_connectweb'

const INTRO_DELAY_MS = 500;

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css'],
})
export class AppComponent {
    title = 'Eliza'
    name: string = '';
    intros: string[] = [];
    statement: string = '';
    answers: string[] = [];
    showSayInput: boolean = false;
    constructor(
        @Inject(ElizaService)
        private client: ObservableClient<typeof ElizaService>
    ) {}

    ngOnInit() {
    }

    onIntroduce(event?: MouseEvent) {
        if (event) { event.stopPropagation(); }
        let resps: string[] = []
        this.client.introduce({name: this.name}).subscribe(
            (next) => {
                resps.push(next.sentence)
            }, 
            (err) => console.log(err), 
            () => {
                setTimeout(() => {
                    this.showSayInput = true;
                }, resps.length * INTRO_DELAY_MS)

                for (var i = 0; i < resps.length; i++) {
                    ;((i) => {
                        setTimeout(() => {
                            this.intros = [...this.intros, resps[i]]
                        }, INTRO_DELAY_MS * (i + 1))
                    })(i)
                }
            }
        );
    }

    onSay(event?: MouseEvent) {
        if (event) { event.stopPropagation(); }
        this.client.say({ sentence: this.statement }).subscribe((next) => {
            this.answers = [...this.answers, next.sentence]
        })
    }
}

<div class="app">
    <header class="app-header">
        <div class="app-title">
            <div>
                <h1>{{ title }}</h1>
            </div>
        </div>
        <p class="prompt-text">What is your name?</p>
        <div>
            <input type="text" class="text-input" [(ngModel)]="name" />
            <button (click)="onIntroduce()">Introduce</button>
        </div>
        <div class="intro-container">
            <p *ngFor="let intro of intros" class="resp-text">{{ intro }}</p>
        </div>
        <div *ngIf="showSayInput">
            <input type="text" class="text-input" [(ngModel)]="statement"  />
            <button (click)="onSay()">Say</button>
        </div>
        <div class="intro-container">
            <p class="resp-text" *ngFor="let answer of answers">{{ answer }}</p>
        </div>
    </header>
</div>

// react/rollup/src/App.tsx
import React, { useState } from 'react'
import './index.css'
import './App.css'
import {
    createPromiseClient,
    createConnectTransport,
} from '@bufbuild/connect-web'
import { ElizaService } from './gen/buf/connect/demo/eliza/v1/eliza_connectweb.js'
import { IntroduceRequest } from './gen/buf/connect/demo/eliza/v1/eliza_pb.js'

function App() {
    const [name, setName] = useState<string>('')
    const [statement, setStatement] = useState<string>('')
    const [intros, setIntros] = useState<string[]>([])
    const [answers, setAnswers] = useState<string[]>([])
    const [showSayInput, setShowSayInput] = useState<boolean>(false)

    const INTRO_DELAY_MS = 500

    // Make the Eliza Service client
    const client = createPromiseClient(
        ElizaService,
        createConnectTransport({
            baseUrl: 'https://demo.connect.build',
        })
    )

    const say = async (sentence: string) => {
        const response = await client.say({
            sentence,
        })

        setAnswers((answers) => [...answers, response.sentence])
    }

    const introduce = async (name: string) => {
        const request = new IntroduceRequest({
            name,
        })

        let resps: string[] = []
        for await (const response of client.introduce(request)) {
            resps.push(response.sentence)
        }

        setTimeout(() => {
            setShowSayInput(true)
        }, resps.length * INTRO_DELAY_MS)

        for (var i = 0; i < resps.length; i++) {
            ;(function (i) {
                setTimeout(function () {
                    setIntros((intro) => [...intro, resps[i]])
                }, INTRO_DELAY_MS * (i + 1))
            })(i)
        }
    }

    const handleNameChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        setName(event.target.value)
    }

    const handleStatementChange = (
        event: React.ChangeEvent<HTMLInputElement>
    ) => {
        setStatement(event.target.value)
    }

    const handleSay = () => {
        say(statement)
    }

    const handleIntroduce = () => {
        introduce(name)
    }

    return (
        <div className="app">
            <header className="app-header">
                <div className="app-title">
                    <div>
                        <h1>Eliza</h1>
                    </div>
                </div>
                <p className="prompt-text">What is your name?</p>
                <div>
                    <input type="text" className="text-input" value={name} onChange={handleNameChange}/>
                    <button onClick={handleIntroduce}>Introduce</button>
                </div>
                <div className="intro-container">
                    {intros.map((intro: string, i:number) => {
                        return (
                            <p className="resp-text" key={`resp${i}`}>
                                {intro}
                            </p>
                        )
                    })}
                </div>
                {showSayInput ? (
                    <div>
                        <input type="text"
                            className="text-input"
                            value={statement}
                            onChange={handleStatementChange}
                        />
                        <button onClick={handleSay}>Say</button>
                    </div>
                ) : (
                    <React.Fragment />
                )}
                <div className="intro-container">
                    {answers.map((answer: string) => {
                        return <p className="resp-text">{answer}</p>
                    })}
                </div>
            </header>
        </div>
    )
}

export default App
